CREATE TABLE peaks (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (50) NOT NULL, 
mountain_id INT NOT NULL, 
CONSTRAINT fk_peaks_mountains
FOREIGN KEY (mountain_id)
REFERENCES mountains(id)
ON DELETE CASCADE);